stages:
  - convert
  - deploy

convert-rules:
  stage: convert
  image: python:3.10
  before_script:
    - echo "Converting sigma rules into Splunk..."
    - pip install --upgrade pip
    - pip install sigma-cli
    - sigma plugin install splunk
  script:
    - mkdir -p ./converted_rules
    - |
      for rule in ./rules/windows/*.yml; do
        filename=$(basename "$rule" .yml).spl
        out_file="./converted_rules/$filename"
        sigma convert -t splunk -p splunk_windows "$rule" -o "$out_file"
      done
  artifacts:
    paths:
      - converted_rules/

deploy-rules:
    stage: deploy
    image: python:3.10
    dependencies: 
        - convert-rules
    before_script:
        - echo "Deploying rules Splunk..."
        - pip install --upgrade pip
        - pip install splunk-sdk
    script:
        - ls converted_rules
        - python3 deploy_to_splunk.py
