stages:
  - convert
  - deploy

convert-rules:
  stage: convert
  image: python:3.13
  before_script:
    - echo "Converting sigma rules into Splunk..."
    - pip install --upgrade pip
    - pip install sigma-cli Jinja2 GitPython
    - sigma plugin install splunk
  script:
    - mkdir -p ./converted_rules
    - python3 ./scripts/convert_to_splunk_alert.py
    - ls
    - ls converted_rules
  artifacts:
    paths:
      - converted_rules/
      - savedsearches.json

deploy-rules:
    stage: deploy
    image: python:3.13
    dependencies: 
        - convert-rules
    before_script:
        - echo "Deploying rules Splunk..."
        - pip install --upgrade pip
        - pip install splunk-sdk
    script:
        - cat savedsearches.json
        - python3 ./scripts/deploy_to_splunk.py
